name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
      - dev-next
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker to Cloudflare
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Configure Wrangler Environment
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: echo "Wrangler configured."

      - name: Set Worker Secrets
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_API_KEY_SECRET_VALUE: ${{ secrets.CF_API_KEY_SECRET }}
          CF_API_EMAIL_SECRET_VALUE: ${{ secrets.CF_API_EMAIL_SECRET }}
          CF_ACCOUNT_ID_SECRET_VALUE: ${{ secrets.CF_ACCOUNT_ID_SECRET }}
          CF_ZONE_ID_SECRET_VALUE: ${{ secrets.CF_ZONE_ID_SECRET }}
        run: |
          echo "Setting CF_API_KEY secret..."
          # Secrets are set for the top-level worker (no --env flag)
          npx wrangler secret put CF_API_KEY <<< "${CF_API_KEY_SECRET_VALUE}"
          echo "Setting CF_API_EMAIL secret..."
          npx wrangler secret put CF_API_EMAIL <<< "${CF_API_EMAIL_SECRET_VALUE}"
          echo "Setting CF_ACCOUNT_ID secret (for worker logic)..."
          npx wrangler secret put CF_ACCOUNT_ID <<< "${CF_ACCOUNT_ID_SECRET_VALUE}"
          echo "Setting CF_ZONE_ID secret..."
          npx wrangler secret put CF_ZONE_ID <<< "${CF_ZONE_ID_SECRET_VALUE}"

      - name: Deploy Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler deploy
